// Code generated by cmd/embed-go-defaults from defaults.json. DO NOT EDIT.

package devportalclient

const (
	// DefaultPublicAPIBaseURL is the production Operational API origin (no trailing slash).
	DefaultPublicAPIBaseURL = "https://api.sybilion.dev"
)
