// Code generated by cmd/embed-go-defaults from defaults.json. DO NOT EDIT.

package sybilion

const (
	// DefaultPublicAPIBaseURL is the production Sybilion API origin (no trailing slash).
	DefaultPublicAPIBaseURL = "https://api.sybilion.dev"
)
