// Command embed-go-defaults reads defaults.json at the repository root and writes defaults_gen.go.
// Run after editing defaults.json: go run ./cmd/embed-go-defaults
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type defaultsFile struct {
	DefaultPublicAPIBaseURL string `json:"defaultPublicApiBaseUrl"`
}

func main() {
	root, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "embed-go-defaults: %v\n", err)
		os.Exit(1)
	}
	path := filepath.Join(root, "defaults.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "embed-go-defaults: read %s: %v\n", path, err)
		os.Exit(1)
	}
	var d defaultsFile
	if err := json.Unmarshal(raw, &d); err != nil {
		fmt.Fprintf(os.Stderr, "embed-go-defaults: json: %v\n", err)
		os.Exit(1)
	}
	d.DefaultPublicAPIBaseURL = strings.TrimSpace(d.DefaultPublicAPIBaseURL)
	if d.DefaultPublicAPIBaseURL == "" {
		fmt.Fprintf(os.Stderr, "embed-go-defaults: defaults.json must set defaultPublicApiBaseUrl\n")
		os.Exit(1)
	}
	out := filepath.Join(root, "defaults_gen.go")
	if err := os.WriteFile(out, []byte(goFile(d)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "embed-go-defaults: write %s: %v\n", out, err)
		os.Exit(1)
	}
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from cwd")
		}
		dir = parent
	}
}

func goFile(d defaultsFile) string {
	return fmt.Sprintf(`// Code generated by cmd/embed-go-defaults from defaults.json. DO NOT EDIT.

package sybilion

const (
	// DefaultPublicAPIBaseURL is the production Sybilion API origin (no trailing slash).
	DefaultPublicAPIBaseURL = %q
)
`, d.DefaultPublicAPIBaseURL)
}
