/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TierConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TierConfig{}

// TierConfig struct for TierConfig
type TierConfig struct {
	// Per-minute cap on general authenticated /api/v1/_* requests at this tier.
	GeneralRpm int32 `json:"general_rpm"`
	// Tier level identifier (0 is the baseline).
	Level int32 `json:"level"`
	// Maximum in-flight async forecast jobs (queued + running) at this tier.
	MaxConcurrentJobs int32 `json:"max_concurrent_jobs"`
	// Minimum lifetime payment in EUR cents to reach this tier.
	MinLifetimePaidCents int64 `json:"min_lifetime_paid_cents"`
	// Minimum number of successful payments to reach this tier.
	MinPaymentCount int32 `json:"min_payment_count"`
	// Minimum single payment in EUR cents to reach this tier; 0 means no constraint.
	MinSinglePaymentCents int64 `json:"min_single_payment_cents"`
	// Per-minute cap on synchronous billed endpoints (e.g. POST /drivers) at this tier.
	SyncBilledRpm int32 `json:"sync_billed_rpm"`
}

type _TierConfig TierConfig

// NewTierConfig instantiates a new TierConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTierConfig(generalRpm int32, level int32, maxConcurrentJobs int32, minLifetimePaidCents int64, minPaymentCount int32, minSinglePaymentCents int64, syncBilledRpm int32) *TierConfig {
	this := TierConfig{}
	this.GeneralRpm = generalRpm
	this.Level = level
	this.MaxConcurrentJobs = maxConcurrentJobs
	this.MinLifetimePaidCents = minLifetimePaidCents
	this.MinPaymentCount = minPaymentCount
	this.MinSinglePaymentCents = minSinglePaymentCents
	this.SyncBilledRpm = syncBilledRpm
	return &this
}

// NewTierConfigWithDefaults instantiates a new TierConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTierConfigWithDefaults() *TierConfig {
	this := TierConfig{}
	return &this
}

// GetGeneralRpm returns the GeneralRpm field value
func (o *TierConfig) GetGeneralRpm() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GeneralRpm
}

// GetGeneralRpmOk returns a tuple with the GeneralRpm field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetGeneralRpmOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneralRpm, true
}

// SetGeneralRpm sets field value
func (o *TierConfig) SetGeneralRpm(v int32) {
	o.GeneralRpm = v
}

// GetLevel returns the Level field value
func (o *TierConfig) GetLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *TierConfig) SetLevel(v int32) {
	o.Level = v
}

// GetMaxConcurrentJobs returns the MaxConcurrentJobs field value
func (o *TierConfig) GetMaxConcurrentJobs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxConcurrentJobs
}

// GetMaxConcurrentJobsOk returns a tuple with the MaxConcurrentJobs field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetMaxConcurrentJobsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConcurrentJobs, true
}

// SetMaxConcurrentJobs sets field value
func (o *TierConfig) SetMaxConcurrentJobs(v int32) {
	o.MaxConcurrentJobs = v
}

// GetMinLifetimePaidCents returns the MinLifetimePaidCents field value
func (o *TierConfig) GetMinLifetimePaidCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MinLifetimePaidCents
}

// GetMinLifetimePaidCentsOk returns a tuple with the MinLifetimePaidCents field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetMinLifetimePaidCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinLifetimePaidCents, true
}

// SetMinLifetimePaidCents sets field value
func (o *TierConfig) SetMinLifetimePaidCents(v int64) {
	o.MinLifetimePaidCents = v
}

// GetMinPaymentCount returns the MinPaymentCount field value
func (o *TierConfig) GetMinPaymentCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinPaymentCount
}

// GetMinPaymentCountOk returns a tuple with the MinPaymentCount field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetMinPaymentCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinPaymentCount, true
}

// SetMinPaymentCount sets field value
func (o *TierConfig) SetMinPaymentCount(v int32) {
	o.MinPaymentCount = v
}

// GetMinSinglePaymentCents returns the MinSinglePaymentCents field value
func (o *TierConfig) GetMinSinglePaymentCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MinSinglePaymentCents
}

// GetMinSinglePaymentCentsOk returns a tuple with the MinSinglePaymentCents field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetMinSinglePaymentCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinSinglePaymentCents, true
}

// SetMinSinglePaymentCents sets field value
func (o *TierConfig) SetMinSinglePaymentCents(v int64) {
	o.MinSinglePaymentCents = v
}

// GetSyncBilledRpm returns the SyncBilledRpm field value
func (o *TierConfig) GetSyncBilledRpm() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SyncBilledRpm
}

// GetSyncBilledRpmOk returns a tuple with the SyncBilledRpm field value
// and a boolean to check if the value has been set.
func (o *TierConfig) GetSyncBilledRpmOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SyncBilledRpm, true
}

// SetSyncBilledRpm sets field value
func (o *TierConfig) SetSyncBilledRpm(v int32) {
	o.SyncBilledRpm = v
}

func (o TierConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TierConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["general_rpm"] = o.GeneralRpm
	toSerialize["level"] = o.Level
	toSerialize["max_concurrent_jobs"] = o.MaxConcurrentJobs
	toSerialize["min_lifetime_paid_cents"] = o.MinLifetimePaidCents
	toSerialize["min_payment_count"] = o.MinPaymentCount
	toSerialize["min_single_payment_cents"] = o.MinSinglePaymentCents
	toSerialize["sync_billed_rpm"] = o.SyncBilledRpm
	return toSerialize, nil
}

func (o *TierConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"general_rpm",
		"level",
		"max_concurrent_jobs",
		"min_lifetime_paid_cents",
		"min_payment_count",
		"min_single_payment_cents",
		"sync_billed_rpm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTierConfig := _TierConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTierConfig)

	if err != nil {
		return err
	}

	*o = TierConfig(varTierConfig)

	return err
}

type NullableTierConfig struct {
	value *TierConfig
	isSet bool
}

func (v NullableTierConfig) Get() *TierConfig {
	return v.value
}

func (v *NullableTierConfig) Set(val *TierConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableTierConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableTierConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTierConfig(val *TierConfig) *NullableTierConfig {
	return &NullableTierConfig{value: val, isSet: true}
}

func (v NullableTierConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTierConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


