/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidationErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorResponse{}

// ValidationErrorResponse struct for ValidationErrorResponse
type ValidationErrorResponse struct {
	Details []ValidationErrorResponseDetailsInner `json:"details"`
	Error string `json:"error"`
}

type _ValidationErrorResponse ValidationErrorResponse

// NewValidationErrorResponse instantiates a new ValidationErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorResponse(details []ValidationErrorResponseDetailsInner, error_ string) *ValidationErrorResponse {
	this := ValidationErrorResponse{}
	this.Details = details
	this.Error = error_
	return &this
}

// NewValidationErrorResponseWithDefaults instantiates a new ValidationErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorResponseWithDefaults() *ValidationErrorResponse {
	this := ValidationErrorResponse{}
	return &this
}

// GetDetails returns the Details field value
func (o *ValidationErrorResponse) GetDetails() []ValidationErrorResponseDetailsInner {
	if o == nil {
		var ret []ValidationErrorResponseDetailsInner
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponse) GetDetailsOk() ([]ValidationErrorResponseDetailsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Details, true
}

// SetDetails sets field value
func (o *ValidationErrorResponse) SetDetails(v []ValidationErrorResponseDetailsInner) {
	o.Details = v
}

// GetError returns the Error field value
func (o *ValidationErrorResponse) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ValidationErrorResponse) SetError(v string) {
	o.Error = v
}

func (o ValidationErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["details"] = o.Details
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ValidationErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"details",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationErrorResponse := _ValidationErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidationErrorResponse)

	if err != nil {
		return err
	}

	*o = ValidationErrorResponse(varValidationErrorResponse)

	return err
}

type NullableValidationErrorResponse struct {
	value *ValidationErrorResponse
	isSet bool
}

func (v NullableValidationErrorResponse) Get() *ValidationErrorResponse {
	return v.value
}

func (v *NullableValidationErrorResponse) Set(val *ValidationErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorResponse(val *ValidationErrorResponse) *NullableValidationErrorResponse {
	return &NullableValidationErrorResponse{value: val, isSet: true}
}

func (v NullableValidationErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


