/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ValidationErrorResponseDetailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorResponseDetailsInner{}

// ValidationErrorResponseDetailsInner struct for ValidationErrorResponseDetailsInner
type ValidationErrorResponseDetailsInner struct {
	Field string `json:"field"`
	Message string `json:"message"`
}

type _ValidationErrorResponseDetailsInner ValidationErrorResponseDetailsInner

// NewValidationErrorResponseDetailsInner instantiates a new ValidationErrorResponseDetailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorResponseDetailsInner(field string, message string) *ValidationErrorResponseDetailsInner {
	this := ValidationErrorResponseDetailsInner{}
	this.Field = field
	this.Message = message
	return &this
}

// NewValidationErrorResponseDetailsInnerWithDefaults instantiates a new ValidationErrorResponseDetailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorResponseDetailsInnerWithDefaults() *ValidationErrorResponseDetailsInner {
	this := ValidationErrorResponseDetailsInner{}
	return &this
}

// GetField returns the Field field value
func (o *ValidationErrorResponseDetailsInner) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseDetailsInner) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *ValidationErrorResponseDetailsInner) SetField(v string) {
	o.Field = v
}

// GetMessage returns the Message field value
func (o *ValidationErrorResponseDetailsInner) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseDetailsInner) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ValidationErrorResponseDetailsInner) SetMessage(v string) {
	o.Message = v
}

func (o ValidationErrorResponseDetailsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationErrorResponseDetailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ValidationErrorResponseDetailsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationErrorResponseDetailsInner := _ValidationErrorResponseDetailsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidationErrorResponseDetailsInner)

	if err != nil {
		return err
	}

	*o = ValidationErrorResponseDetailsInner(varValidationErrorResponseDetailsInner)

	return err
}

type NullableValidationErrorResponseDetailsInner struct {
	value *ValidationErrorResponseDetailsInner
	isSet bool
}

func (v NullableValidationErrorResponseDetailsInner) Get() *ValidationErrorResponseDetailsInner {
	return v.value
}

func (v *NullableValidationErrorResponseDetailsInner) Set(val *ValidationErrorResponseDetailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorResponseDetailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorResponseDetailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorResponseDetailsInner(val *ValidationErrorResponseDetailsInner) *NullableValidationErrorResponseDetailsInner {
	return &NullableValidationErrorResponseDetailsInner{value: val, isSet: true}
}

func (v NullableValidationErrorResponseDetailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorResponseDetailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


