/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiV1UsageGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1UsageGet200Response{}

// ApiV1UsageGet200Response struct for ApiV1UsageGet200Response
type ApiV1UsageGet200Response struct {
	Pagination Pagination `json:"pagination"`
	UsageEvents []UsageEvent `json:"usage_events"`
}

type _ApiV1UsageGet200Response ApiV1UsageGet200Response

// NewApiV1UsageGet200Response instantiates a new ApiV1UsageGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1UsageGet200Response(pagination Pagination, usageEvents []UsageEvent) *ApiV1UsageGet200Response {
	this := ApiV1UsageGet200Response{}
	this.Pagination = pagination
	this.UsageEvents = usageEvents
	return &this
}

// NewApiV1UsageGet200ResponseWithDefaults instantiates a new ApiV1UsageGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1UsageGet200ResponseWithDefaults() *ApiV1UsageGet200Response {
	this := ApiV1UsageGet200Response{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *ApiV1UsageGet200Response) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ApiV1UsageGet200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ApiV1UsageGet200Response) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetUsageEvents returns the UsageEvents field value
func (o *ApiV1UsageGet200Response) GetUsageEvents() []UsageEvent {
	if o == nil {
		var ret []UsageEvent
		return ret
	}

	return o.UsageEvents
}

// GetUsageEventsOk returns a tuple with the UsageEvents field value
// and a boolean to check if the value has been set.
func (o *ApiV1UsageGet200Response) GetUsageEventsOk() ([]UsageEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.UsageEvents, true
}

// SetUsageEvents sets field value
func (o *ApiV1UsageGet200Response) SetUsageEvents(v []UsageEvent) {
	o.UsageEvents = v
}

func (o ApiV1UsageGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1UsageGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["usage_events"] = o.UsageEvents
	return toSerialize, nil
}

func (o *ApiV1UsageGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"usage_events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiV1UsageGet200Response := _ApiV1UsageGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiV1UsageGet200Response)

	if err != nil {
		return err
	}

	*o = ApiV1UsageGet200Response(varApiV1UsageGet200Response)

	return err
}

type NullableApiV1UsageGet200Response struct {
	value *ApiV1UsageGet200Response
	isSet bool
}

func (v NullableApiV1UsageGet200Response) Get() *ApiV1UsageGet200Response {
	return v.value
}

func (v *NullableApiV1UsageGet200Response) Set(val *ApiV1UsageGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1UsageGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1UsageGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1UsageGet200Response(val *ApiV1UsageGet200Response) *NullableApiV1UsageGet200Response {
	return &NullableApiV1UsageGet200Response{value: val, isSet: true}
}

func (v NullableApiV1UsageGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1UsageGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


