/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the CheckoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutRequest{}

// CheckoutRequest struct for CheckoutRequest
type CheckoutRequest struct {
	// Min 500 (€5.00) by default; server-enforced
	AmountCents *int64 `json:"amount_cents,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewCheckoutRequest instantiates a new CheckoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutRequest() *CheckoutRequest {
	this := CheckoutRequest{}
	var currency string = "eur"
	this.Currency = &currency
	return &this
}

// NewCheckoutRequestWithDefaults instantiates a new CheckoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutRequestWithDefaults() *CheckoutRequest {
	this := CheckoutRequest{}
	var currency string = "eur"
	this.Currency = &currency
	return &this
}

// GetAmountCents returns the AmountCents field value if set, zero value otherwise.
func (o *CheckoutRequest) GetAmountCents() int64 {
	if o == nil || IsNil(o.AmountCents) {
		var ret int64
		return ret
	}
	return *o.AmountCents
}

// GetAmountCentsOk returns a tuple with the AmountCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutRequest) GetAmountCentsOk() (*int64, bool) {
	if o == nil || IsNil(o.AmountCents) {
		return nil, false
	}
	return o.AmountCents, true
}

// HasAmountCents returns a boolean if a field has been set.
func (o *CheckoutRequest) HasAmountCents() bool {
	if o != nil && !IsNil(o.AmountCents) {
		return true
	}

	return false
}

// SetAmountCents gets a reference to the given int64 and assigns it to the AmountCents field.
func (o *CheckoutRequest) SetAmountCents(v int64) {
	o.AmountCents = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CheckoutRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutRequest) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CheckoutRequest) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *CheckoutRequest) SetCurrency(v string) {
	o.Currency = &v
}

func (o CheckoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AmountCents) {
		toSerialize["amount_cents"] = o.AmountCents
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableCheckoutRequest struct {
	value *CheckoutRequest
	isSet bool
}

func (v NullableCheckoutRequest) Get() *CheckoutRequest {
	return v.value
}

func (v *NullableCheckoutRequest) Set(val *CheckoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutRequest(val *CheckoutRequest) *NullableCheckoutRequest {
	return &NullableCheckoutRequest{value: val, isSet: true}
}

func (v NullableCheckoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


